semi: false
singleQuote: true
jsxSingleQuote: true
"arrowParens": "always"
"bracketSpacing": true
"jsxBracketSameLine": false
"printWidth": 120
"requirePragma": false
"tabWidth": 2
"trailingComma": "es5"
"useTabs": false
